# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uisample.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1122, 825)
        self.importButton = QtWidgets.QPushButton(Dialog)
        self.importButton.setGeometry(QtCore.QRect(1020, 10, 93, 28))
        self.importButton.setObjectName("importButton")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 1001, 271))
        self.tableView.setObjectName("tableView")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 290, 256, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.rangeRadio = QtWidgets.QRadioButton(Dialog)
        self.rangeRadio.setGeometry(QtCore.QRect(30, 650, 71, 19))
        self.rangeRadio.setObjectName("rangeRadio")
        self.countRadio = QtWidgets.QRadioButton(Dialog)
        self.countRadio.setGeometry(QtCore.QRect(110, 650, 71, 19))
        self.countRadio.setObjectName("countRadio")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 550, 181, 31))
        self.comboBox.setObjectName("comboBox")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(320, 550, 91, 31))
        self.addButton.setObjectName("addButton")
        self.runPrecleaningButton = QtWidgets.QPushButton(Dialog)
        self.runPrecleaningButton.setGeometry(QtCore.QRect(10, 590, 281, 31))
        self.runPrecleaningButton.setObjectName("runPrecleaningButton")
        self.drawButton = QtWidgets.QPushButton(Dialog)
        self.drawButton.setGeometry(QtCore.QRect(300, 660, 101, 31))
        self.drawButton.setObjectName("drawButton")
        self.weightInput = QtWidgets.QLineEdit(Dialog)
        self.weightInput.setGeometry(QtCore.QRect(200, 550, 111, 31))
        self.weightInput.setObjectName("weightInput")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 520, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 520, 71, 21))
        self.label_2.setObjectName("label_2")
        self.classInput = QtWidgets.QLineEdit(Dialog)
        self.classInput.setGeometry(QtCore.QRect(180, 660, 111, 31))
        self.classInput.setObjectName("classInput")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 630, 91, 21))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 290, 581, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.importButton.setText(_translate("Dialog", "Import"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "속성명"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "가중치"))
        self.rangeRadio.setText(_translate("Dialog", "범위"))
        self.countRadio.setText(_translate("Dialog", "개수"))
        self.addButton.setText(_translate("Dialog", "추가"))
        self.runPrecleaningButton.setText(_translate("Dialog", "가중치 설정 완료"))
        self.drawButton.setText(_translate("Dialog", "확인"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">속성명</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">가중치</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">분류군 수</span></p></body></html>"))
